# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiltroLog
                                 A QGIS plugin
 Um plugin desenvolvido para auxiliar na filtragem de arquivos de log criados ao importar um kmz para o qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-29
        copyright            : (C) 2025 by ® Guilherme Guedes - Geotecnologia 
        email                : guedesguilherme01912@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
# -*- coding: utf-8 -*-


def classFactory(iface):
    """
    Função obrigatória de entrada do QGIS; retorna a instância do diálogo.
    """
    from .log_plugin import LogPluginDialog
    return LogPluginDialog(iface)