# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiltroLogDialog
                                 A QGIS plugin
 Um plugin desenvolvido para auxiliar na filtragem de arquivos de log criados ao importar um kmz para o qgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-29
        git sha              : $Format:%H$
        copyright            : (C) 2025 by ® Guilherme Guedes - Geotecnologia 
        email                : guedesguilherme01912@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

class FiltroLogDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("FiltroLogDialog")
        Dialog.resize(400, 200)
        self.pushButton_FiltrarLogs = QtWidgets.QPushButton(Dialog)
        self.pushButton_FiltrarLogs.setGeometry(QtCore.QRect(150, 150, 100, 30))
        self.pushButton_FiltrarLogs.setObjectName("pushButton_FiltrarLogs")
        self.lineEdit_NomeDaCamadaFiltrada = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_NomeDaCamadaFiltrada.setGeometry(QtCore.QRect(50, 50, 300, 30))
        self.lineEdit_NomeDaCamadaFiltrada.setObjectName("lineEdit_NomeDaCamadaFiltrada")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("FiltroLogDialog", "Filtrar Logs"))
        self.pushButton_FiltrarLogs.setText(_translate("FiltroLogDialog", "Filtrar e Mesclar"))
